text={  "Reggel felébredtem. Mit tegyek?":"I woke up in the morning. What should I do now?",
        "fogmosás":"Brushing my teeth",
        "reggeli":"Breakfast",
        "öltözés":"Get dressed",
        "66-os parancs":"Road 66",
        "Elmegyek fogatmosni. Sikálom rendesen, ahogy kell!":"I'm going to brush my teeth. I brush it properly, as I should!",
        "Kellene valamit enni! Anya csinált valamit? Nézzük meg!":"You should eat something! Did mom do something? Let's look at!",
        "Kissé hűvös van, Kelle valami ruha! \nFelveszek egy nadrágot, meg egy pólót!":"It's a bit chilly, I need some clothes! \nI'll put on some pants and a t-shirt!",
        "Ma koncertre megyek, elötte dönteni kéne, hogy itthon vagy egy étteremben eszek.":"Today I'm going to a concert, before that I should decide whether to eat at home or in a restaurant.",
        "Itthon ettem, most elindulok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?":"I've eaten at home, now I'm off to the concert, should I buy a ticket on the way or at the venue?",
        "Étteremben ettem, most elinduok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?":"I ate at a restaurant, now I'm going to the concert, should I buy a ticket on the way or at the venue?",
        "otthon":"home",
        "étteremben":"in the restaurant",
        "odaúton":"on the way there",
        "helyszínen":"buy locally",
        "koncert":"concert",
        "helyszínen veszem a jegyet, beállok a sorba.":"I buy my ticket on the spot, get in line.",
        "ideúton vettem a jegyet, nem kell sorban állnom.":"I bought my ticket on the way here, I don't have to queue.",
        "kártyával fizetek":"I pay by card",
        "készpénzel fizetek":"I pay with cash",
        "iszok valamit":"have a drink",
        "megpróbálok minél közelebb jutni a színpadhoz":"I try to get as close to the stage as possible",
        "Fizettem, mit tegyek?":"What should I do?",
        "vodka alma":"vodka apple",
        "jager":"Jägermeister",
        "Cappy":"Cappy",
        "Mit igyak?":"What should I drink?",
        "Koncert után hova menjek?":"Where to go after a concert?",
        "Haza":"Go home",
        "Mekibe":"To McDonalds",
        "Haza megyek, majd lefekszek aludni":"I'm going home and going to bed",
        "Vége":"The End",
        "Elmegyek Mekibe majd utánna haza.":"I will go to McDonalds and then home.",
        "Sikerült ideérnem időben ezert második sorban állok":"I managed to get here on time so I'm standing in the second row",
        "Vége a koncertnek":"End of the concert",
    }
