text={  "Reggel felébredtem. Mit tegyek?":"Reggel felébredtem. Mit tegyek most?",
        "fogmosás":"fogmosás",
        "reggeli":"reggeli",
        "öltözés":"öltözés",
        "66-os parancs":"66-os parancs",
        "Elmegyek fogatmosni. Sikálom rendesen, ahogy kell!":"Elmegyek fogatmosni. Sikálom rendesen, ahogy kell!",
        "Kellene valamit enni! Anya csinált valamit? Nézzük meg!":"Kellene valamit enni! Anya csinált valamit? Nézzük meg!",
        "Kissé hűvös van, Kelle valami ruha! \nFelveszek egy nadrágot, meg egy pólót!":"Kissé hűvös van, Kelle valami ruha! \nFelveszek egy nadrágot, meg egy pólót!",
        "Ma koncertre megyek, elötte dönteni kéne, hogy itthon vagy egy étteremben eszek.":"Ma koncertre megyek, elötte dönteni kéne, hogy itthon vagy egy étteremben eszek.",
        "Itthon ettem, most elindulok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?":"Itthon ettem, most elindulok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?",
        "Étteremben ettem, most elinduok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?":"Étteremben ettem, most elinduok a koncertre, jegyet az odaúton vagy a helyszínen vegyek?",
        "otthon":"otthon",
        "étteremben":"étteremben",
        "odaúton":"odaúton",
        "helyszínen":"helyszínen",
        "koncert":"koncert",
        "helyszínen veszem a jegyet, beállok a sorba.":"helyszínen veszem a jegyet, beállok a sorba.",
        "ideúton vettem a jegyet, nem kell sorban állnom.":"ideúton vettem a jegyet, nem kell sorban állnom.",
        "kártyával fizetek":"kártyával fizetek",
        "készpénzel fizetek":"készpénzel fizetek",
        "iszok valamit":"iszok valamit",
        "megpróbálok minél közelebb jutni a színpadhoz":"megpróbálok minél közelebb jutni a színpadhoz",
        "Fizettem, mit tegyek?":"Fizettenm mit tegyek?",
        "vodka alma":"vodka alma",
        "jager":"jager",
        "Cappy":"Cappy",
        "Mit igyak?":"Mit igyak?",
        "Koncert után hova menjek?":"Koncert után hova menjek?",
        "Haza":"Haza",
        "Mekibe":"Mekibe",
        "Haza megyek, majd lefekszek aludni":"Haza megyek, majd lefekszek aludni",
        "Vége":"Vége",
        "Elmegyek Mekibe majd utánna haza.":"Elmegyek Mekibe majd utánna haza.",
        "Sikerült ideérnem időben ezert második sorban állok":"Sikerült ideérnem időben ezert második sorban állok",
        "Vége a koncertnek":"Vége a koncertnek",
    }
